version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  weather-station-01:
    build:
      context: ./stations
    environment:
      STATION_ID: WS-01
      INTERVAL: 5

  weather-station-02:
    build:
      context: ./stations
    environment:
      STATION_ID: WS-02
      INTERVAL: 7

  weather-station-03:
    build:
      context: ./stations
    environment:
      STATION_ID: WS-03
      INTERVAL: 3
